debug: true

default_avatar: "https://cdn.luogu.com.cn/upload/usericon/1.png"

database:
  database: confessionwall
  host: "127.0.0.1"
  port: 3306
  user: root
  password: 123456

jwt:
  secret: "wP3-sN68>g&lVgG4-8>J9)"
  lifespan: 24
